/* AI先机 V3 增量样式：保留原有视觉，仅增强实时情报、研究报告与财商启蒙 */
.live-shell{background:linear-gradient(180deg,rgba(37,99,235,.06),rgba(255,255,255,0));border:1px solid #dfe8ff;border-radius:28px;padding:22px}.live-toolbar{display:flex;justify-content:space-between;align-items:flex-start;gap:18px;margin-bottom:18px}.live-status{display:flex;align-items:center;gap:9px;color:var(--muted);font-size:13px}.pulse-dot{width:9px;height:9px;border-radius:999px;background:var(--success);box-shadow:0 0 0 0 rgba(22,163,74,.45);animation:pulse 2s infinite}.live-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px}.live-card{display:block;background:var(--card);border:1px solid var(--border);border-radius:18px;padding:18px;transition:.2s ease;position:relative}.live-card:hover{transform:translateY(-2px);box-shadow:var(--shadow)}.live-card h3{font-size:17px;line-height:1.4;margin:8px 0 7px}.live-card p{margin:0;color:var(--muted);font-size:14px}.live-meta{display:flex;flex-wrap:wrap;gap:8px;margin-top:14px;color:#667085;font-size:12px}.live-meta span{background:var(--bg);border:1px solid var(--border);border-radius:999px;padding:4px 8px}.source-ledger-mini{margin-top:12px;padding-top:11px;border-top:1px dashed var(--border);font-size:12px;color:var(--muted)}
.research-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:16px}.research-card{background:var(--card);border:1px solid var(--border);border-radius:22px;padding:22px;display:flex;flex-direction:column;gap:14px}.research-top{display:flex;align-items:flex-start;justify-content:space-between;gap:14px}.research-top h3{margin:7px 0 0;font-size:21px;line-height:1.35}.research-score{min-width:58px;height:58px;border-radius:18px;display:grid;place-items:center;background:var(--primary-soft);color:var(--primary);font-weight:850}.verdict{padding:14px 16px;border-radius:15px;background:#f8fafc;border:1px solid var(--border);font-weight:650}.research-kpis{display:grid;grid-template-columns:repeat(3,1fr);gap:8px}.research-kpis div{padding:10px;border:1px solid var(--border);border-radius:13px;background:var(--bg)}.research-kpis small{display:block;color:var(--muted);font-size:11px}.research-kpis b{font-size:13px}.research-card details{border-top:1px solid var(--border);padding-top:12px}.research-card summary{cursor:pointer;font-weight:750}.source-list{display:grid;gap:8px;margin-top:10px}.source-list a{display:block;padding:10px 12px;border:1px solid var(--border);border-radius:12px;font-size:13px;background:var(--bg)}.source-list a:hover{border-color:#b8c9ff}.research-actions{display:flex;gap:9px;flex-wrap:wrap;margin-top:auto}
.hackathon-city-row{display:flex;gap:8px;overflow:auto;padding-bottom:4px;margin-bottom:16px}.hackathon-city-row button{border:1px solid var(--border);background:var(--card);padding:8px 12px;border-radius:999px;white-space:nowrap;color:var(--muted)}.hackathon-city-row button.active{color:#fff;background:var(--primary);border-color:var(--primary)}
.finance-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:12px}.finance-card{background:var(--card);border:1px solid var(--border);border-radius:18px;padding:18px;min-height:210px}.finance-card span{font-size:11px;font-weight:750;color:var(--primary)}.finance-card h3{margin:8px 0;font-size:18px}.finance-card p{font-size:14px;color:var(--muted)}.finance-card footer{margin-top:14px;padding-top:12px;border-top:1px dashed var(--border);font-size:13px;font-weight:700}
.wave-banner{position:relative;overflow:hidden;border-radius:30px;background:linear-gradient(135deg,#111827,#1d4ed8 70%,#60a5fa);color:#fff;padding:44px}.wave-banner:after{content:"";position:absolute;width:300px;height:300px;border-radius:50%;right:-90px;top:-120px;border:60px solid rgba(255,255,255,.08)}.wave-banner h2{font-size:clamp(28px,4vw,48px);line-height:1.15;margin:0 0 14px;max-width:800px}.wave-banner p{max-width:820px;color:rgba(255,255,255,.82);font-size:17px}.wave-actions{display:flex;gap:10px;flex-wrap:wrap;margin-top:24px}.wave-actions button,.wave-actions a{padding:11px 16px;border-radius:13px;border:1px solid rgba(255,255,255,.28);background:rgba(255,255,255,.1);color:#fff;font-weight:750}.wave-actions .solid{background:#fff;color:#111827}
.report-entry{display:grid;grid-template-columns:1.05fr .95fr;gap:24px;align-items:stretch}.report-copy,.report-preview{border:1px solid var(--border);border-radius:24px;padding:26px;background:var(--card)}.report-copy h2{font-size:32px;line-height:1.25;margin:8px 0 12px}.report-preview{background:linear-gradient(180deg,#f7faff,#fff)}.report-preview ul{padding-left:20px;color:var(--muted)}.soft-pay{font-size:12px;color:var(--muted);margin-top:12px}.questionnaire{display:grid;gap:18px}.question-block{padding:16px;border:1px solid var(--border);border-radius:16px}.question-block h4{margin:0 0 10px}.option-grid{display:flex;flex-wrap:wrap;gap:8px}.option-grid label{cursor:pointer}.option-grid input{position:absolute;opacity:0}.option-grid span{display:block;padding:8px 11px;border:1px solid var(--border);border-radius:999px;font-size:13px}.option-grid input:checked+span{background:var(--primary);border-color:var(--primary);color:#fff}.report-result{padding:20px;border-radius:18px;background:var(--primary-soft);margin-top:18px}.report-result h3{margin-top:0}
.v3-modal{position:fixed;inset:0;z-index:120;background:rgba(15,23,42,.58);display:grid;place-items:center;padding:20px}.v3-modal[hidden]{display:none}.v3-dialog{width:min(760px,100%);max-height:88vh;overflow:auto;background:var(--card);border-radius:24px;padding:26px;position:relative}.v3-dialog-close{position:sticky;float:right;top:0;width:38px;height:38px;border-radius:12px;border:1px solid var(--border);background:var(--card)}
.copyright-note{font-size:12px;color:var(--muted);padding:12px 14px;border:1px dashed var(--border);border-radius:14px;background:var(--bg)}
@keyframes pulse{70%{box-shadow:0 0 0 9px rgba(22,163,74,0)}100%{box-shadow:0 0 0 0 rgba(22,163,74,0)}}
[data-theme="dark"] .live-shell{background:linear-gradient(180deg,rgba(59,130,246,.12),transparent);border-color:#293550}[data-theme="dark"] .verdict{background:#151c2b}[data-theme="dark"] .report-preview{background:linear-gradient(180deg,#151d31,#111827)}
@media(max-width:900px){.live-grid,.research-grid,.report-entry{grid-template-columns:1fr}.finance-grid{grid-template-columns:repeat(2,minmax(0,1fr))}.wave-banner{padding:30px}}
@media(max-width:600px){.live-toolbar{display:block}.live-status{margin-top:10px}.finance-grid{grid-template-columns:1fr}.research-kpis{grid-template-columns:1fr}.wave-banner{padding:24px;border-radius:22px}.report-copy,.report-preview{padding:20px}}
